package com.upbapps.moviemap.ui.theme

const val tk: String = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MmQzZTlmZTM2MGYxZDdjZmQxNDMwNjljYjgyZmI5MiIsIm5iZiI6MTc0NjQwODEyOC45NDQsInN1YiI6IjY4MTgxMmMwYWVmMmU1M2M2ZWQ0Y2I5ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.doIdIc-Dk95w2SLqLsiR-FSZRrkzdbBg9PajkEN-fVM"